# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SchoolProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SchoolProject
  pod 'SnapKit', '~> 3.2.0'
  pod 'Alamofire', '~> 4.4.0'
  pod "PromiseKit", "~> 4.0"
  
  target 'SchoolProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SchoolProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
